language: python
sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - python-dev
    - libssl-dev
    - libffi-dev
python:
  - "2.7"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1 BRANCH=$(cat meta/deployment/branch) COMMIT_HASH=$(cat meta/deployment/commit_hash)
script:
  - bash meta/deployment/deploy.sh